package laiebei.terminal.dbm.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import laiebei.terminal.dbm.domain.CabinetInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CABINET_INFO".
*/
public class CabinetInfoDao extends AbstractDao<CabinetInfo, Long> {

    public static final String TABLENAME = "CABINET_INFO";

    /**
     * Properties of entity CabinetInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Version = new Property(1, String.class, "version", false, "VERSION");
        public final static Property Gallery = new Property(2, int.class, "gallery", false, "GALLERY");
    }

    private DaoSession daoSession;


    public CabinetInfoDao(DaoConfig config) {
        super(config);
    }
    
    public CabinetInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CABINET_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"VERSION\" TEXT," + // 1: version
                "\"GALLERY\" INTEGER NOT NULL );"); // 2: gallery
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CABINET_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CabinetInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(2, version);
        }
        stmt.bindLong(3, entity.getGallery());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CabinetInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(2, version);
        }
        stmt.bindLong(3, entity.getGallery());
    }

    @Override
    protected final void attachEntity(CabinetInfo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CabinetInfo readEntity(Cursor cursor, int offset) {
        CabinetInfo entity = new CabinetInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // version
            cursor.getInt(offset + 2) // gallery
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CabinetInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVersion(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGallery(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CabinetInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CabinetInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CabinetInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
